# Generated by Django 5.1.15 on 2026-09-29 21:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAcquisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('utm_source', models.CharField(blank=True, max_length=100)),
                ('utm_medium', models.CharField(blank=True, max_length=100)),
                ('utm_campaign', models.CharField(blank=True, max_length=200)),
                ('utm_content', models.CharField(blank=True, max_length=200)),
                ('utm_term', models.CharField(blank=True, max_length=200)),
                ('yclid', models.CharField(blank=True, max_length=100)),
                ('referrer', models.CharField(blank=True, max_length=500)),
                ('landing_page', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='acquisition', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Источник регистрации',
                'verbose_name_plural': 'Источники регистраций',
            },
        ),
    ]
