# Generated by Django 6.0.6 on 2026-07-06 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditLedgerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('topup', 'Пополнение'), ('spend', 'Списание'), ('refund', 'Возврат')], max_length=10)),
                ('amount', models.IntegerField()),
                ('balance_after', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='creditledger',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='creditledger',
            name='user',
        ),
        migrations.AlterModelOptions(
            name='creditpackage',
            options={'ordering': ['sort_order']},
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='raw_callback',
            new_name='raw_result_payload',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='credits',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='robokassa_inv_id',
        ),
        migrations.AddField(
            model_name='creditpackage',
            name='currency',
            field=models.CharField(default='RUB', max_length=3),
        ),
        migrations.AddField(
            model_name='creditpackage',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='payment',
            name='credits_to_grant',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='payment',
            name='currency',
            field=models.CharField(default='RUB', max_length=3),
        ),
        migrations.AddField(
            model_name='payment',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='payment',
            name='is_test',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='payment',
            name='robokassa_operation_id',
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name='creditpackage',
            name='title',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='payment',
            name='status',
            field=models.CharField(choices=[('pending', 'Ожидает оплаты'), ('paid', 'Оплачен'), ('failed', 'Не оплачен'), ('expired', 'Истёк')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='payment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['status', 'created_at'], name='billing_pay_status_f64990_idx'),
        ),
        migrations.AddField(
            model_name='creditledgerentry',
            name='payment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.payment'),
        ),
        migrations.AddField(
            model_name='creditledgerentry',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='credit_entries', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='CreditLedger',
        ),
    ]
