# Generated by Django 5.1.15 on 2026-09-29 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_promo_code_charset_validator'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationpackage',
            name='badge',
            field=models.CharField(blank=True, help_text='Бейдж на карточке, например «Популярный»', max_length=40),
        ),
        migrations.AddField(
            model_name='generationpackage',
            name='badge_en',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AddField(
            model_name='generationpackage',
            name='features',
            field=models.TextField(blank=True, help_text='Пункты на карточке — по одному в строке'),
        ),
        migrations.AddField(
            model_name='generationpackage',
            name='features_en',
            field=models.TextField(blank=True, help_text='То же на английском, в том же порядке'),
        ),
        migrations.AddField(
            model_name='generationpackage',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Выделен визуально и выбран по умолчанию на странице оплаты'),
        ),
        migrations.AddField(
            model_name='generationpackage',
            name='slug',
            field=models.SlugField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name='generationpackage',
            name='title_en',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='generationpackage',
            name='visibility',
            field=models.CharField(choices=[('public', 'Всем'), ('paid_only', 'Только уже платившим')], default='public', max_length=10),
        ),
    ]
