# Generated by Django 5.1.15 on 2026-09-29 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_upsell_package'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='purchase_reported_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='utm_campaign',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='payment',
            name='utm_content',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='payment',
            name='utm_medium',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='utm_source',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='payment',
            name='utm_term',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='payment',
            name='yclid',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
