# Generated by Django 5.1.15 on 2026-09-23 21:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Carousel',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic', models.TextField(help_text='О чём карусель — формулировка пользователя')),
                ('slides_count', models.PositiveSmallIntegerField(default=7)),
                ('theme', models.CharField(choices=[('light', 'Светлая'), ('dark', 'Тёмная'), ('blue', 'Синяя')], default='light', max_length=20)),
                ('handle', models.CharField(blank=True, max_length=40)),
                ('slides', models.JSONField(blank=True, default=list)),
                ('caption', models.TextField(blank=True)),
                ('image_keys', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'В очереди'), ('processing', 'Генерируется'), ('done', 'Готово'), ('failed', 'Ошибка')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carousels', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Карусель',
                'verbose_name_plural': 'Карусели',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='carousels_c_user_id_22922b_idx')],
            },
        ),
    ]
