# Generated by Django 5.1.15 on 2026-09-24 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carousels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='design',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='carousel',
            name='theme',
            field=models.CharField(default='light', max_length=20),
        ),
    ]
