# Generated by Django 5.1.15 on 2026-09-22 19:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_order_customization_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('web', 'Сайт'), ('telegram', 'Telegram-бот')], default='web', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='review', to='photos.order')),
            ],
            options={
                'verbose_name': 'Отзыв о генерации',
                'verbose_name_plural': 'Отзывы о генерациях',
                'ordering': ['-created_at'],
            },
        ),
    ]
