# Generated by Django 5.1.15 on 2026-09-23 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_order_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderreview',
            name='is_public',
            field=models.BooleanField(default=False, verbose_name='Показывать на главной'),
        ),
    ]
