# Generated by Django 5.1.15 on 2026-09-29 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_order_review_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedresult',
            name='is_free_preview',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='generatedresult',
            name='preview_s3_key',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='generatedresult',
            name='unlocked',
            field=models.BooleanField(default=False, help_text='Превью оплачено — доступен оригинал в HD'),
        ),
        migrations.AddField(
            model_name='generatedresult',
            name='unlocked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='client_ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='is_free_preview',
            field=models.BooleanField(default=False),
        ),
    ]
