# Generated by Django 5.1.15 on 2026-10-01 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0005_free_preview'),
    ]

    operations = [
        migrations.AddField(
            model_name='generatedresult',
            name='reminder_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
