# Generated by Django 5.1.15 on 2026-10-03 18:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_preview_reminder'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='device',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='user_agent',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.CreateModel(
            name='FunnelEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('stage', models.CharField(db_index=True, max_length=40)),
                ('session_id', models.CharField(blank=True, db_index=True, max_length=64)),
                ('device', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('desktop', 'Десктоп'), ('other', 'Другое')], default='other', max_length=10)),
                ('user_agent', models.CharField(blank=True, max_length=300)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funnel_events', to='photos.order')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='funnel_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Этап воронки',
                'verbose_name_plural': 'Воронка /workstation',
                'ordering': ['-created_at'],
            },
        ),
    ]
